version: "3.8"

services:
  mysql:
    container_name: mysql_db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Nathanjames12345_*
      MYSQL_DATABASE: springapidb
      MYSQL_USER: root
      MYSQL_PASSWORD: Nathanjames12345_*
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3000:3306"
    networks:
      - springapi_web_net
    restart: on-failure

  app:
    build: .
    image: morsecodes/springapi
    ports:
      - "8000:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/springai
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Nathanjames12345_*
      PORT: "8080"
    depends_on:
      - mysql
    networks:
      - springapi_web_net
    volumes:
      - .:/usr/src/app
    restart: on-failure:3

networks:
  springapi_web_net:
    driver: bridge

volumes:
  mysql_data: